try-fix: 发现init.sh中vim-plug的hash漏了

diff --git a/.github/workflows/test-ci.yaml b/.github/workflows/test-ci.yaml
--- a/.github/workflows/test-ci.yaml
+++ b/.github/workflows/test-ci.yaml
@@ -17,13 +17,16 @@ jobs:
       - name: 安装依赖
         run: sudo apt-get install zsh
 
-      - name: 运行 init.sh 并检查直接安装字体情况
+      - name: 运行 init.sh 并检查是否安装得当
         env:
           payload: ${{ matrix.payload  }}
         run: |
           echo -e "$payload" > tmp_inp.txt
-          cat tmp_inp.txt
-          zsh init.sh < tmp_inp.txt && rm tmp_inp.txt
+          if [[ ! -s tmp_inp.txt ]]; then
+            echo "invalid inp-file size was detected!"
+            exit 1
+          fi 
+          zsh init.sh < tmp_inp.txt && rm tmp_inp.txt && \
           cd ~/.vim/ && ls autoload colors fonts/*
 
   python-remove-test:
@@ -42,8 +45,7 @@ jobs:
             echo "123" > file
             touch -t 202001011145 file 
           done
-          cd .. && python clean_vimview.py
-          unset test_files && ls view/
+          cd .. && python clean_vimview.py && unset test_files && ls view/
 
 
 
